id: P006733
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:19:56.207946
source_metadata:
  id: bdr:W1AC36
  title: ཐར་མདོ།  འདའ་ཀ་ཡེ་ཤེས་ཀྱི་མདོ།  སྡིག་བཤགས་གསེར་གྱི་སྤུ་གྲི།
  author: ''
  volumes:
    280721349e7c4a8892ffa1003865d00e:
      image_group_id: I2PD18191
      title: ''
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
