id: IA8EB7C47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:22:59+00:00'
last_modified: '2022-06-08T06:28:30.693699+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC36
  title: ཐར་མདོ།  འདའ་ཀ་ཡེ་ཤེས་ཀྱི་མདོ།  སྡིག་བཤགས་གསེར་གྱི་སྤུ་གྲི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4456':
      image_group_id: I2PD18191
      title: ''
      total_pages: 314
      order: 1
      base_file: 4456.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
